### Nuke Database
POST http://localhost:3000/debug/nuke

### Get packs

GET http://localhost:3000/packs

### Get packs with offset

GET http://localhost:3000/packs?offset=1

### Get packs with limit

GET http://localhost:3000/packs?limit=1

### Get packs by categories

GET http://localhost:3000/packs?categories[]=party

### Create a pack

POST http://localhost:3000/packs
Content-Type: application/json

{
  "name": "Jon's Awesome Pack",
  "categories": ["fun", "awesome", "party"],
  "questions": [
      "q1",
      "q2",
      "q3"
  ],
  "public": false
}

### Delete a pack

DELETE http://localhost:3000/packs/1

### Edit a pack
PUT http://localhost:3000/packs/1
Content-Type: application/json

{
  "name": "Gary's Awesome Pack",
  "categories": ["awesome", "party", "random"],
  "questions": [
      "q1",
      "q2",
      "q4"
  ],
  "public": true
}

### Get all categories

GET http://localhost:3000/categories